[platformio]
core_dir = .platformio
src_dir = RFLink

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep
lib_deps =
    bblanchon/ArduinoJson @ 6.18.5
    boblemaire/asyncHTTPrequest @ 1.2.2
    esp32async/ESPAsyncWebServer @ 3.6.0
    jgromes/RadioLib @ 5.6
    knolleary/PubSubClient @ 2.8
    olikraus/U8g2 @ 2.36.18
    https://api.github.com/repos/cpainchaud/rflink-webui/tarball/2ab3f0cae74dff7770fe69fbc9ec89709d3d4dc2 ; 0.0.0

[esp32]
platform = platformio/espressif32 @ 7.0.1
lib_deps =
    ${env.lib_deps}
    esp32async/AsyncTCP @ 3.3.2
monitor_filters = esp32_exception_decoder
debug_tool = esp-prog
debug_init_break = tbreak setup
board_build.filesystem = littlefs
board_build.partitions = partitions/esp32_4MB_LittleFS-327k.csv
build_src_filter =
    +<*>
    -<Plugins>

[esp8266]
platform = platformio/espressif8266 @ 4.1.0
lib_deps =
    ${env.lib_deps}
    esp32async/ESPAsyncTCP @ 2.0.0
    marvinroger/ESP8266TrueRandom @ 1.0
monitor_filters = esp8266_exception_decoder
build_src_filter =
    +<*>
    -<Plugins>

[env:esp32dev]
extends = esp32
board = esp32dev
build_flags =
;   -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;   -DDEBUG_RFLINK_CONFIG
;   -DRADIOLIB_DEBUG
;   -DRFLINK_MQTT_DISABLED
;   -DRFLINK_OTA_ENABLED
;   -DRFLINK_OTA_PASSWORD='"'${sysenv.OTA_SEC}'"'
;   -DRFLINK_PORTAL_DISABLED
;   -DRFLINK_SERIAL2NET_DEBUG
;   -DRFLINK_SIGNAL_RSSI_DEBUG
    -DRFLINK_WIFI_ENABLED

[env:esp32-c3-devkitm-1]
extends = esp32
board = esp32-c3-devkitm-1 
build_flags =
;   -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;   -DDEBUG_RFLINK_CONFIG
;   -DRADIOLIB_DEBUG
;   -DRFLINK_MQTT_DISABLED
;   -DRFLINK_OTA_ENABLED
;   -DRFLINK_OTA_PASSWORD='"'${sysenv.OTA_SEC}'"'
;   -DRFLINK_PORTAL_DISABLED
;   -DRFLINK_SERIAL2NET_DEBUG
;   -DRFLINK_SIGNAL_RSSI_DEBUG
    -DRFLINK_WIFI_ENABLED

[env:heltec_wifi_lora_32_V2]
extends = esp32
board = heltec_wifi_lora_32_V2
build_flags =
    -DPIN_RF_RX_CS=18
    -DPIN_RF_RX_DATA=34
    -DPIN_RF_RX_RESET=14
    -DRFLink_default_Radio_HardwareType=HardwareType::HW_SX1278_t
    -DRFLINK_WIFI_ENABLED

[env:d1_mini]
extends = esp8266
board = d1_mini
build_flags =
    -DARDUINOJSON_USE_LONG_LONG
;   -DRADIOLIB_DEBUG
;   -DRFLINK_MQTT_DISABLED
;   -DRFLINK_MQTT_CLIENT_SSL_DISABLED ; disable SSL capabilities in PubSubClient to save memory
;   -DRFLINK_PORTAL_DISABLED
    -DRFLINK_WIFI_ENABLED

[env:esp8285] ; Sonoff RF Bridge
extends = esp8266
board = esp8285
lib_ignore =
    RadioLib
    rtl_433
build_flags =
    -DARDUINOJSON_USE_LONG_LONG
    -DFIRMWARE_UPGRADE_VIA_WEBSERVER_DISABLED
;   -DRADIOLIB_DEBUG
;   -DRFLINK_MQTT_DISABLED
;   -DRFLINK_MQTT_CLIENT_SSL_DISABLED      ; disable SSL capabilities in PubSubClient to save memory
    -DRFLINK_NO_RADIOLIB_SUPPORT
;   -DRFLINK_PORTAL_DISABLED
    -DRFLINK_USE_HARDCODED_RADIO_PINS_ONLY ; strips out all the radio pin config code and saves memory
    -DRFLINK_WIFI_ENABLED
    -DTARGET_BOARD_ESP8285
