name: Build

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  context:
    name: Context
    runs-on: ubuntu-latest
    outputs:
      pio-environments: ${{ steps.platformio.outputs.environments }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          version-file: pyproject.toml
          python-version: 3.11
          activate-environment: true

      - name: Set up Python packages
        run: uv sync --only-group nodejs --only-group platformio

      - name: PlatformIO environments
        id: platformio
        run: echo "environments=$(pio project config --json-output | jq -c '[.[] | .[0] | select(startswith("env:")) | sub("^env:"; "")]')" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    needs: context
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ${{ fromJSON(needs.context.outputs.pio-environments) }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Cache for PlatformIO
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: platformio-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('platformio.ini') }}
          path: .platformio/.cache

      - name: Set up uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          version-file: pyproject.toml
          python-version: 3.11
          activate-environment: true

      - name: Set up PlatformIO
        run: uv sync --no-dev

      - name: PlatformIO build
        run: pio run -e ${{ matrix.environment }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          version-file: pyproject.toml
          python-version: 3.14
          activate-environment: true

      - name: Set up PlatformIO
        run: uv sync --only-group platformio

      - name: PlatformIO lint
        run: |
          OUTPUT=$(pio project config --lint --json-output)
          echo "$OUTPUT"
          if [ "$OUTPUT" != "{'errors': [], 'warnings': []}" ]; then
            exit 1
          fi
